HzyAdmin/Areas/Admin/Controllers/Sys/ChangePwdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HzyAdmin.Areas.Admin.Controllers.Sys
{
    //
    using Aop;
    using Common;
    using Models.SysClass;
    using Logic.SysClass;
    using System.Collections;

    public class ChangePwdController : BaseController
    {
        //
        // GET: /ManageSys/ChangePwd/
        public AccountLogic _Logic { get; set; }

        protected override void Init()
        {
            this.MenuID = "Z-150";
        }

        public override ActionResult Index()
        {
            ViewData["userName"] = _Logic.Get(Account.UserID).User_Name;
            return View();
        }

        [HttpPost]
        public ActionResult ChangePwd(string oldpwd, string newpwd, string newlypwd)
        {
            _Logic.ChangePwd(oldpwd, newpwd, newlypwd);
            return this.Success();
        }

    }
}

HzyAdmin/Areas/Admin/Controllers/Sys/CreateCodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HzyAdmin.Areas.Admin.Controllers.Sys
{
    //
    using Aop;
    using Common;
    using Models.SysClass;
    using Logic.SysClass;
    using System.Collections;

    public class CreateCodeController : BaseController
    {
        // 根据表 生成 代码
        // GET: /SysManage/CreateCode/
        public Sys_CreateCodeLogic _Logic { get; set; }

        protected override void Init()
        {
            this.MenuID = "Z-160";
        }

        public override ActionResult Index()
        {
            ViewData["DbSetCode"] = _Logic.CreateDbSetCode();
            return base.Index();
        }

        /// <summary>
        /// 获取数据库中所有的表和字段
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetZTreeAllTable()
        {
            return this.Success(new { status = 1, value = _Logic.GetZTreeAllTable() });
        }

        /// <summary>
        /// 保存
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Save(FormCollection fc)
        {
            var Type = fc["ClassType"];
            var Url = (fc["Url"] == null ? Server.MapPath("/Content/CreateFile") : fc["Url"]);
            var Str = fc["Str"];
            var Table = fc["Table"];
            var isall = fc["isall"].ToBool();
            var Template = Server.MapPath("/Content/Template/");

            _Logic.Save(Type, Url, Template, Str, isall, Table);
            return this.Success();
        }



    }
}

HzyAdmin/Areas/Admin/Controllers/Sys/FunctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HzyAdmin.Areas.Admin.Controllers.Sys
{
    //
    using Aop;
    using Common;
    using Models.SysClass;
    using Logic.SysClass;
    using System.Collections;

    public class FunctionController : BaseController
    {
        // 功能管理
        // GET: /SysManage/Function/
        public Sys_FunctionLogic _Logic { get; set; }

        protected override void Init()
        {
            this.MenuID = "Z-120";
        }

        #region  基本操作，增删改查

        /// <summary>
        /// 获取列表数据
        /// </summary>
        /// <param name="PageIndex"></param>
        /// <param name="PageSize"></param>
        /// <returns></returns>
        [NonAction]
        public override PagingEntity GetPagingEntity(Hashtable query, int page = 1, int rows = 20)
        {
            //获取列表
            return _Logic.GetDataSource(query, page, rows);
        }

        /// <summary>
        /// 保存
        /// </summary>
        /// <returns></returns>
        [AopCheckEntity]
        [HttpPost]
        public ActionResult Save(Sys_Function model)
        {
            this.KeyID = _Logic.Save(model);
            return this.Success(new { status = 1, ID = KeyID });
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(string Ids)
        {
            _Logic.Delete(Ids);
            return this.Success();
        }

        /// <summary>
        /// 查询根据ID
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult LoadForm(string ID)
        {
            return this.Success(_Logic.LoadForm(ID.ToGuid()));
        }

        #endregion  基本操作，增删改查

    }
}

HzyAdmin/Areas/Admin/Controllers/Sys/MenuFunctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HzyAdmin.Areas.Admin.Controllers.Sys
{
    //
    using Aop;
    using Common;
    using Models.SysClass;
    using Logic.SysClass;
    using System.Collections;

    public class MenuFunctionController : BaseController
    {
        // 菜单功能
        // GET: /ManageSys/MenuFunction/
        public Sys_MenuLogic _Logic { get; set; }

        protected override void Init()
        {
            this.MenuID = "Z-130";
        }

        public override ActionResult Info()
        {
            return View(db.Find<Sys_Function>().OrderBy(w => w.Function_Num).ToList());
        }

        #region  基本操作，增删改查

        /// <summary>
        /// 获取列表数据
        /// </summary>
        /// <param name="PageIndex"></param>
        /// <param name="PageSize"></param>
        /// <returns></returns>
        [NonAction]
        public override PagingEntity GetPagingEntity(Hashtable query, int page = 1, int rows = 20)
        {
            //获取列表
            return _Logic.GetDataSource(query, page, rows);
        }

        /// <summary>
        /// 保存
        /// </summary>
        /// <returns></returns>
        [AopCheckEntity]
        [HttpPost]
        public ActionResult Save(Sys_Menu model, string _Sys_Function_List)
        {
            this.KeyID = _Logic.Save(model, _Sys_Function_List);
            return this.Success(new
            {
                status = 1,
                ID = this.KeyID
            });
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(string Ids)
        {
            _Logic.Delete(Ids);
            return this.Success();
        }

        /// <summary>
        /// 查询根据ID
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult LoadForm(string ID)
        {
            return this.Success(_Logic.LoadForm(ID.ToGuid()));
        }
        #endregion  基本操作，增删改查

        /// <summary>
        /// 获取菜单和功能树
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetMenuAndFunctionTree()
        {
            return Success(new
            {
                status = 1,
                value = _Logic.GetMenuZTree()
            });
        }

        /// <summary>
        /// 保存菜单功能
        /// </summary>
        /// <returns></returns>
        //[HttpPost]
        //public ActionResult SaveMenuFunction(string nodes)
        //{
        //    _Sys_MenuBL.SaveMenuFunction(nodes);
        //    return this.Success();
        //}


    }
}

HzyAdmin/Areas/Admin/Controllers/Sys/PowerControlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HzyAdmin.Areas.Admin.Controllers.Sys
{
    public class PowerControlController : Controller
    {
        //权限控制
        // GET: /ManageSys/PowerControl/

        public ActionResult Index()
        {
            return PartialView();
        }

    }
}

HzyAdmin/Areas/Admin/Controllers/Sys/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HzyAdmin.Areas.Admin.Controllers.Sys
{
    //
    using Aop;
    using Common;
    using Models.SysClass;
    using Logic.SysClass;
    using System.Collections;

    public class RoleController : BaseController
    {
        //角色管理
        // GET: /ManageSys/Role/
        public Sys_RoleLogic _Logic { get; set; }

        protected override void Init()
        {
            this.MenuID = "Z-110";
        }
        
        #region  基本操作，增删改查

        /// <summary>
        /// 获取列表数据
        /// </summary>
        /// <param name="PageIndex"></param>
        /// <param name="PageSize"></param>
        /// <returns></returns>
        [NonAction]
        public override PagingEntity GetPagingEntity(Hashtable query, int page = 1, int rows = 20)
        {
            //获取列表
            return _Logic.GetDataSource(query, page, rows);
        }

        /// <summary>
        /// 新增
        /// </summary>
        /// <returns></returns>
        [AopCheckEntity]
        [HttpPost]
        public ActionResult Save(Sys_Role model)
        {
            this.KeyID = _Logic.Save(model);
            return this.Success(new
            {
                status = 1,
                ID = this.KeyID
            });
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(string Ids)
        {
            _Logic.Delete(Ids);
            return this.Success();
        }

        /// <summary>
        /// 查询根据ID
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult LoadForm(string ID)
        {
            return this.Success(_Logic.LoadForm(ID.ToGuid()));
        }

        #endregion  基本操作，增删改查

    }
}

HzyAdmin/Areas/Admin/Controllers/Sys/RoleFunctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HzyAdmin.Areas.Admin.Controllers.Sys
{
    //
    using Aop;
    using Common;
    using Models.SysClass;
    using Logic.SysClass;
    using System.Collections;

    public class RoleFunctionController : BaseController
    {
        // 角色功能
        // GET: /ManageSys/RoleFunction/
        public Sys_RoleMenuFunctionLogic _Logic { get; set; }

        protected override void Init()
        {
            this.MenuID = "Z-140";
        }

        public override ActionResult Index()
        {
            return View(db.Find<Sys_Role>().OrderBy(w => w.Role_Num).ToList());
        }
        #region  基本操作，增删改查

        /// <summary>
        /// 获取角色菜单功能
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetRoleMenuFunctionTree(string RoleId)
        {
            return this.Success(new
            {
                status = 1,
                value = _Logic.GetRoleMenuFunctionZTree(RoleId.ToGuid())
            });
        }

        /// <summary>
        /// 保存角色功能
        /// </summary>
        /// <param name="json"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Save(string Sys_RoleMenuFunction_List, string RoleId)
        {
            _Logic.SaveFunction(Sys_RoleMenuFunction_List, RoleId.ToGuid());
            return this.Success();
        }
        #endregion 基本操作，增删改查
    }
}

HzyAdmin/Areas/Admin/Controllers/Sys/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HzyAdmin.Areas.Admin.Controllers.Sys
{
    //
    using Aop;
    using Common;
    using Models.SysClass;
    using Logic.SysClass;
    using System.Collections;

    public class UserController : BaseController
    {
        // 用户管理
        // GET: /ManageSys/User/
        public Sys_UserLogic _Logic { get; set; }

        protected override void Init()
        {
            this.MenuID = "Z-100";
        }

        #region  基本操作，增删改查

        /// <summary>
        /// 获取列表数据
        /// </summary>
        /// <param name="PageIndex"></param>
        /// <param name="PageSize"></param>
        /// <returns></returns>
        [NonAction]
        public override PagingEntity GetPagingEntity(Hashtable query, int page = 1, int rows = 20)
        {
            //获取列表
            return _Logic.GetDataSource(query, page, rows);
        }

        /// <summary>
        /// 保存
        /// </summary>
        /// <returns></returns>
        [AopCheckEntity]
        [HttpPost]
        public ActionResult Save(Sys_User model, string Role_ID)
        {
            this.KeyID = _Logic.Save(model, new Sys_UserRole() { UserRole_RoleID = Role_ID.ToGuid() });
            return this.Success(new
            {
                status = 1,
                ID = this.KeyID
            });
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(string Ids)
        {
            _Logic.Delete(Ids);
            return this.Success();
        }

        /// <summary>
        /// 查询根据ID
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult LoadForm(string ID)
        {
            return this.Success(_Logic.LoadForm(ID.ToGuid()));
        }
        #endregion  基本操作，增删改查

    }
}

HzyAdmin/Areas/Admin/Views/Sys/User/Index.cshtml
@{
    var _FindBack = Request.QueryString["findback"].ToStr();
}


<div class="page animation-fade">

    <div class="page-content">
        <!--高级检索部分-->
        <div class="panel" id="panelSearch">
            <div class="panel-heading">
                <h3 class="panel-title">高级检索</h3>
            </div>
            <div class="panel-body">
                <form action="javascript:void(0)" class="form-row">
                    <div class="col-sm-3">
                        <h4 class="example-title">用户名</h4>
                        <input type="text" class="form-control" name="User_Name" placeholder="请输入用户名">
                    </div>
                    <div class="col-sm-3">
                        <h4 class="example-title">登录名</h4>
                        <input type="text" class="form-control" name="User_LoginName" placeholder="请输入登录名">
                    </div>
                </form>

            </div>
            <div class="panel-footer text-right">
                <button class="btn btn-primary" onclick="adminList.search()">检索</button>&nbsp;&nbsp;
                <button class="btn btn-success" onclick="adminList.resetSearch()">重置</button>&nbsp;&nbsp;
                <button class="btn btn-danger" onclick="adminList.panelSearch()">关闭</button>
            </div>
        </div>

        <!--列表-->
        <div class="panel">
            <div class="panel-heading">
                <div class="col-sm-12 pl-25 pr-25 pt-15 pb-10">
                    <button type="button" class="btn btn-primary" onclick="window.location=window.location">
                        <i class="fa fa-rotate-right"></i>&nbsp;刷新
                    </button>
                    <button type="button" class="btn btn-primary" data-power="Search" name="search" onclick="adminList.panelSearch()">
                        <i class="fa fa-search"></i>&nbsp;检索
                    </button>
                    <button type="button" class="btn btn-primary" data-power="Add" name="add" onclick="App.Form('add')">
                        <i class="fa fa-plus"></i>&nbsp;添加
                    </button>
                    <button type="button" class="btn btn-primary" data-power="Edit" name="edit" onclick="App.Form('edit')" disabled="disabled">
                        <i class="fa fa-pencil"></i>&nbsp;修改
                    </button>
                    <button type="button" class="btn btn-primary" data-power="Delete" name="delete" onclick="App.Delete()" disabled="disabled">
                        <i class="fa fa-trash"></i>&nbsp;删除
                    </button>
                    <a class="btn btn-primary" target="_blank" href="" data-power="GetExcel" name="getExcel" onclick="App.ExportExcel()">
                        <i class="fa fa-file-excel-o"></i>&nbsp;导出 Excel
                    </a>
                    @if (_FindBack == "Multiple")
                    {
                        <!--查找带回按钮-->
                        <button type="button" class="btn btn-success" onclick="adminList.findBack();">
                            <i class="fa fa-check"></i>&nbsp;带回
                        </button>
                    }

                </div>
            </div>
            <div class="panel-body container-fluid pb-0">

                <!--表格-->
                <table class="table table-hover" id="bootStrapTable"></table>

            </div>
        </div>
    </div>
</div>

@section css{
    <style type="text/css">
    </style>
}
@section js{
    <script src="~/Resource/Admin/lib/bootstrap-table-develop/src/bootstrap-table.js"></script>
    <script src="~/Resource/Admin/lib/bootstrap-table-develop/src/locale/bootstrap-table-zh-CN.js"></script>
    <script src="~/Resource/Admin/js/admin-list.js"></script>
    <script type="text/javascript">
        var FormID = "@ViewData["formWindowName"]";
        var thisWindowName = "@ViewData["thisWindowName"]";

        $(function () {

            App.Init();

        });


        var App = {
            Init: function () {
                admin.ajax({
                    url: "@Url.Action("GetDataSource")",
                    data: { rows: 1 },
                    success: function (r) {
                        var adminBootStrapTable = adminList.bootStrapTable({
                            url: "@Url.Action("GetDataSource")",
                            columns: r.column
                        });
                    }
                });
            },
            Form: function (tag) {
                var rows = adminList.selectRows();
                var url = "@Url.Action("Info")";
                if (tag == "add") {
                    url = url + "/?ID=";
                } else {
                    url = url + "/?ID=" + rows[0]._ukid;
                }
                adminList.form({
                    id: FormID,
                    parentIframeName: thisWindowName,
                    url: url,
                    width: "500px",
                    height: "600px",
                    btn: false,
                });
            },
            Delete: function () {
                adminList.delete('@Url.Action("Delete")', function () {
                    App.Refresh();
                    console.log("删除完成!");
                });
            },
            ExportExcel: function () {
                adminList.exportExcel('@Url.Action("ExportExcel")');
            },
            Refresh: function (data) {
                adminList.refresh(data);
            }

        };

    </script>
}

HzyAdmin/Areas/Admin/Views/Sys/User/Info.cshtml
@{
    var KeyId = Request.QueryString["ID"];
}
<div class="page-content animated fadeInDown">
    <div class="container-fluid  pb-100">
        <div class="row" id="form">
            <!--检索面板-->

            <div class="col-sm-12">
                <h4 class="example-title">用户名</h4>
                <input type="text" class="form-control" name="User_Name" data-bind="value:User_Name" placeholder="请输入用户名" />
            </div>

            <div class="col-sm-12">
                <h4 class="example-title">登录名</h4>
                <input type="text" class="form-control" name="User_LoginName" data-bind="value:User_LoginName" placeholder="请输入登录名" />
            </div>

            <div class="col-sm-12">
                <h4 class="example-title">登录密码</h4>
                <input type="text" class="form-control" name="User_Pwd" data-bind="value:User_Pwd" placeholder="请输入登录密码" />
            </div>

            <div class="col-sm-12">
                <h4 class="example-title">邮箱地址</h4>
                <input type="text" class="form-control" name="User_Email" data-bind="value:User_Email" placeholder="请输入邮件" />
            </div>

            @(UI.FindBack<Sys_Role, Sys_Role>(
                                                w => w.Role_Name, w => w.Role_ID,
                                                Url.Action("Index", "Role", new { findback = "1" }),
                                                "App.FindBack.CallBack(row,'Role')",
                                                "App.FindBack.CallBack(null,'Role');", 12
                                            ))


        </div>

    </div>
</div>
<!--按钮-->
<div class="my-ButtonBar text-right">
    <button type="button" class="btn btn-success" data-bind="visible: !App.IsAdd()" onclick="adminForm.resetUrl(null)">新增</button>
    <button class="btn btn-primary" onclick="App.Save()">提交</button>
    <button class="btn btn-danger" onclick="admin.layer.close(admin.getLayerIframeIndex());">关闭</button>
</div>
@section css{
}
@section js{
    <script src="~/Resource/Admin/lib/Ko/Knockout-3.4.2.debug.js"></script>
    <script src="~/Resource/Admin/js/admin-form.js"></script>
    <script type="text/javascript">
        var KeyId = '@KeyId';
        model = new vModel();
        $(function () {
            ko.applyBindings(model);//注册vModel
            App.Load();
        });

        var App = {
            IsAdd: function () {
                return !KeyId;
            },
            Load: function () {
                adminForm.load({
                    KeyId: KeyId,
                    url: "@Url.Action("LoadForm")",
                    callBack: function (r) {

                    }
                });
            },
            Save: function () {
                adminForm.Save({
                    url: "@Url.Action("Save")"
                });
            },
            FindBack: {
                CallBack: function (row, tag, dom) {
                    if (row != null && row.length > 0) row = row[0];
                    if (tag == "Role") {
                        model.Role_ID(row ? row._ukid : "");
                        model.Role_Name(row ? row.Role_Name : "");
                    }
                }
            }
        };

        //User_ID, User_Name, User_LoginName, User_Pwd, User_Email, User_CreateTime
        function vModel() {
            @(UI.CreateKOViewModel(new Sys_User(),new Sys_Role()))
            //this.User_ID = ko.observable("");
            //this.User_Name = ko.observable("");
            //this.User_LoginName = ko.observable("");
            //this.User_Pwd = ko.observable("");
            //this.User_Email = ko.observable("");

            //this.Role_ID = ko.observable("");
            //this.Role_Name = ko.observable("");
        }
    </script>
}